# Generated by Django 5.1.1 on 2024-09-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stok',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
